# Generated by Django 3.2.7 on 2021-09-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musoc',
            new_name='Music',
        ),
    ]
